services:
    start-team.ir:
        build:
            context: ./
            dockerfile: steam.dockerfile
            # args:
            #    WWWGROUP: '${WWWGROUP}'
        tty: true 
        #environment:
                #    WWWUSER: '${WWWUSER}'
        volumes:
            - '${STEAM}:/var/www/${STEAM}'
            - '${STEAM}/supervisord.conf:/etc/supervisord.conf'
              # command: ["sh -c php-fpm && supervisord"]
        command: /start.sh
                # bash -c "php-fpm && supervisord -c /etc/supervisord.conf"
        networks:
            - sail
        depends_on:
            - mysql
            - redis
              #            - meilisearch
              #            - selenium

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - ./data/mysql/my.cnf:/etc/my.cnf
            - ../backup:/backup
            - ./data/log:/var/log/mysql
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            #    meilisearch:
            #            image: 'getmeili/meilisearch:latest'
            #            volumes:
            #                - 'sail-meilisearch:/meili_data'
            #            networks:
            #                - sail
            #            healthcheck:
            #                test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            #                retries: 3
            #                timeout: 5s
            #    mailhog:
            #            image: 'mailhog/mailhog:latest'
            #            networks:
            #                - sail
            #    selenium:
            #            image: 'selenium/standalone-chrome'
            #            volumes:
            #                - '/dev/shm:/dev/shm'
            #            networks:
            #                - sail
networks:
    sail:
            external: true
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
